### ISSUE TITLE
Add unit testing for Matrix Functions

### ISSUE THREAD

**Issue by dwardu89** [dwardu89/Matrices#3]

**Comment by AbdulR3hman** [comment]
Hi @dwardu89 

I'd like to claim this issue, I started working on test cases for the Matrix class itself, I'd like to carry on and develop some cases for the function class after. 

Is that alright?

**Comment by dwardu89** [comment]
Yes go ahead. @AbdulR3hman it's yours.

**Comment by dwardu89** [comment]
Can you use the autolinking procedure to link to the issue so i can assign it to you .

Documentation on how to do it is here.    https://help.github.com/articles/autolinked-references-and-urls/
